### PR TITLE
pet command: show item received when obtaining an Olmlet

### LINKED ISSUE #37: Show item received when obtaining an olmet with the +pet command

### PR DESCRIPTION
**Pull request by Alexsuperfly**
closes #37

### CODE REVIEW

**Comment by Alexsuperfly** [comment]
closing until #40 is merged since that creates a much better way to do this.

**Comment by Alexsuperfly** [comment]
should be good to go, also added it for finish and kill command alongside the dedicated pet command

**Comment by gc** [comment]
If you'd like to update this PR and verify it's working I'll merge ASAP, sorry for the late reply!

**Comment by Alexsuperfly** [comment]
rebased, heres some images to show what it looks like on output

**Comment by gc** [comment]
LGTM! Thanks :)

**Pull request merged**
