### PR TITLE
change +bank --text --full to show amount then item for copy paste

### PR DESCRIPTION
**Pull request by duracell33**

### CODE REVIEW

**Comment by gc** [comment]
this doesnt make sense to me, do people want this? having the name first makes more sense to me

**Comment by duracell33** [comment]
Discord_fjroPVgAyb
i was just looking for easy suggestions

**Comment by gc** [comment]
As discussed in discord i think this should be opt-in with a msg flag

**Comment by gc** [comment]
Closed due to inactivity

**Pull request closed without merging**
